import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { ChooseTeamPage} from "../chooseteam/chooseteam";

@Component({
  selector: 'page-codex',
  templateUrl: 'codex.html'
})
export class CodexPage {

  constructor(public navCtrl: NavController) {

  }

  navigateToChooseTeamPage(codex): void {

    var leaders = new Array();
    var members= new Array();
    var monsters= new Array();

    //DO FOR ALL CODEXES INCLUDED = DAVID HELP
    if (codex.includes("harlequins")) {
      codex = "Harlequins";
      let c1 = {name:"Shadowseer",description:"Illusion, misdirection and terror are the psychic tools at the disposal of the Shadowseer. Wherever the Shadowseer treads on the battlefield discipline collapses, replaced by a bedlam of screams, gibbering and panicked, aimless gunfire. Through it all strides the Shadowseer – an island of sinister calm in an ocean of madness.",M:"8 in.",WS:"2+",BS:"2+",S:3,T:3,W:5,A:3,Ld:9,Sv:"7+"};
      let c2 = {name:"Troupe Master",description:"Each Troupe Master directs their Players with the skill of an impresario and the strategic genius of a seasoned general. It is they that decides where the Troupe goes next, what dance is performed, and what messages they deliver.",M:"8 in.",WS:"2+",BS:"2+",S:3,T:3,W:5,A:5,Ld:9,Sv:"6+"};
      leaders = [c1,c2];
      let c3 = {name:"Troupe",description:"In battle, Harlequin Troupe move fast and hit hard, relying on speed and skill to annihilate the enemy before they even have time to raise their guns. Once in combat, the Harlequin are in their element, performing a lethal dance of death while their masks shimmer with their foe’s worst fears.",M:"8 in.",WS:"3+",BS:"3+",S:3,T:3,W:1,A:4,Ld:8,Sv:"6+"};
      let c4 = {name:"Death Jester",description:"Embracing the role of Death in its entirety, there is no mercy in the heart of a Death Jester. His outsize shuriken cannon reaps a deadly toll on his enemies as each round, impregnated with virulent biotoxins, causes its victims’ metabolisms to spectacularly detonate.",M:"8 in.",WS:"2+",BS:"2+",S:3,T:3,W:5,A:4,Ld:9,Sv:"6+"};
      let c5 = {name:"Solitaire",description:"None, even amongst the Harlequins, know the limits of the Solitaire’s abilities. Tales exist of these supernatural killers running up sheer fortress walls, spilling from the shadows inside locked bunkers, even slowing time itself. For any who stand in the Solitaire’s way, death is destined.",M:"8 in.",WS:"2+",BS:"2+",S:3,T:3,W:5,A:8,Ld:9,Sv:"6+"};
      members = [c3,c4,c5];
      let c6 = {name:"Skyweaver",description:"Heavily armed and incredibly fast, squads of Skyweavers outmanoeuvre their foes before cutting them to pieces with concentrated firepower. Their ripping streams of shuriken fire and crackling bolts of electromagnetic energy slaughter foot troops and reduce enemy tanks to sparking wrecks with equal ease.",M:"16 in.",WS:"3+",BS:"3+",S:3,T:4,W:4,A:3,Ld:8,Sv:"4+"};
      let c7 = {name:"Starweaver",description:"Starweavers streak across the battlefield as a storm of shattered light, relying upon a mixture of velocity and misdirection to confound the enemy’s aim. These swift attack vehicles have a transport platform at their rear capable of bearing a Harlequin Troupe into battle.",M:"16 in.",WS:"3+",BS:"3+",S:5,T:5,W:6,A:3,Ld:8,Sv:"4+"};
      let c8 = {name:"Voidweaver",description:"Boasting a veritable arsenal of heavy weaponry, Voidweavers leave flaming devastation in their wake. Their every salvo sees enemies punched off their feet as storms of shuriken scream through the air, and enemy tanks are vaporised by the deadly prismatic cannon.",M:"16 in.",WS:"3+",BS:"3+",S:5,T:5,W:6,A:3,Ld:8,Sv:"4+"};
      monsters = [c6,c7,c8];
    }
    else if (codex.includes("drukhari")) {
      codex = "Drukhari";
      let c1 = {name:"Haemonculus",description:"Haemonculi are deranged flesh-sculptors that dwell in the dank bowels of Commorragh. They are master torturers, expert poisoners and dark alchemists that are capable of transcending death itself.",M:"7 in.",WS:"2+",BS:"2+",S:3,T:4,W:5,A:5,Ld:8,Sv:"6+"};
      let c2 = {name:"Succubus",description:"The Succubi are the ruling elite of the Wych Cults. Impossibly elegant and beautiful, they stalk through the mayhem of battle as if born to it. They regularly take the lead in the war against realspace, not only for the feast of plunder, but also to hunt the champions of the lesser races and defeat them in showy displays of sheer skill.",M:"8 in.",WS:"2+",BS:"2+",S:3,T:3,W:5,A:4,Ld:8,Sv:"6+"};
      let c3 = {name:"Archon",description:"The Archons are the masters of the Drukhari Kabals. Regal and monstrous in equal measure, each wields the power to enslave worlds and destroy civilisations. Archons have fed upon the pain of so many others that it takes true atrocity to invigorate them, so they must lead ever more raids against realspace.",M:"8 in.",WS:"2+",BS:"2+",S:3,T:3,W:5,A:5,Ld:9,Sv:"5+"};
      let c4 = {name:"Beastmaster",description:"Over the millennia since Commorragh's founding its sand-filled arenas have drunk the blood of millions. Each arena has witnessed countless spectacles of perversity and death, but there is one gladiatorial favourite that never fades in popularity - the wild hunts of the Beastmasters.",M:"0 in.",WS:"0+",BS:"0+",S:0,T:0,W:0,A:0,Ld:0,Sv:"0+"};
      let c5 = {name:"Lhamaean",description:"An Archon's courtesans will take many strange forms; however the mysterious sisterhood of Lhilitu are desired above all others, for they are poisoners without equal. The presence of a Lhamaean can ensure a supply of the most virulent toxins, which she will share with her Archon before each realspace raid. It is said that even a kiss blown upon the wind by a Lhamaean can kill in seconds.",M:"8 in.",WS:"3+",BS:"3+",S:3,T:3,W:3,A:2,Ld:8,Sv:"5+"};
      leaders = [c1,c2,c3,c4,c5];
      let c6 = {name:"Incubi",description:"The Incubi are an order of Drukhari that hone themselves for war and war alone. They are warriors of the highest calibre, whose sole goal is to kill as often as possible. They are highly valued as bodyguards and shock troops, and they take a cold joy in proving their deadly skill in times of war.",M:"7 in.",WS:"2+",BS:"3+",S:3,T:3,W:2,A:4,Ld:9,Sv:"3+"};
      let c7 = {name:"Mandrake",description:"The exact nature of the Mandrakes is unknown and no one, including the Drukhari themselves, truly know what they are. Some speculate that they are shadows brought to life, whilst others believe them to be an unholy union of Aeldari and Daemon. Whatever their origin, one thing is certain: they are a terrifying foe.",M:"8 in.",WS:"3+",BS:"3+",S:4,T:3,W:1,A:3,Ld:8,Sv:"7+"};
      let c8 = {name:"Wyche",description:"In the craft of murder, Wyches have no equal. In battle, Wyches feed upon screams of pain. With combat drugs coursing through their veins, Wyches roll, backflip and pirouette out of harm's way, stabbing through visors and neck-joints, slicing open a throat here and piercing a heart there.",M:"8 in.",WS:"3+",BS:"3+",S:3,T:3,W:1,A:2,Ld:8,Sv:"6+"};
      let c9 = {name:"Sslyth",description:"The Sslyth are the favoured bodyguards of Drukhari Archons because, unlike the Drukhari themselves, the Sslyth are 'almost' totally loyal. These hulking serpent-bodied warrior-fiends have two sets of arms, which means they've got plenty of guns and blades, all of them razor sharp and ready to slice and dice. As such, they're perfect for protecting the Archon from any would-be assassins.",M:"8 in.",WS:"3+",BS:"3+",S:5,T:5,W:4,A:3,Ld:2,Sv:"5+"};
      let c10 = {name:"Wrack",description:"As attendants and servants to the Haemonculi, each Wrack is an abhorrent example of his master's surgical craftsmanship, an individual cut apart and refashioned into a walking instrument of torture. Upon the field of battle they will defend their creator with their lives, utilizing all manner of disturbing, exotic weapons.",M:"7 in.",WS:"3+",BS:"3+",S:3,T:4,W:1,A:2,Ld:7,Sv:"6+"};
      let c11 = {name:"Kabalite Warrior",description:"Warriors of the Kabals form the beating heart of each Drukhari strike force. They are the cruellest and most rapacious of their caste, hungry for power and thirsty for the suffering of others. Kabalite Warriors are merciless fighters of murderous intent.",M:"7 in.",WS:"3+",BS:"3+",S:3,T:3,W:1,A:2,Ld:8,Sv:"5+"};
      let c12 = {name:"Scourge",description:"A rich and daring Drukhari may surrender himself to the Haemonculi, requesting that his bones be hollowed out, that bands of new muscle be grafted onto his torso, and powerful wings and adrenaline dispensers be attached to his shoulders so that he is capable of true flight. The Kabal overlords pay handsomely for these veteran warriors to fight for them and as a result the Scourges will often equip themselves with the best weaponry and armour that they can find.",M:"14 in.",WS:"3+",BS:"3+",S:3,T:3,W:1,A:2,Ld:8,Sv:"4+"};
      let c13 = {name:"Hellion",description:"Hellions are airborne killers. Feral Drukhari, they descend upon their prey in a flurry of hooked blades before hurtling away to safety. Hellions ride to war upon skyboards, single-pilot anti-gravity boards, and pump their systems full of combat drugs. They are crazed terror troops who swoop into the midst of the foe, screaming curses and severing limbs with their murderously sharp hellglaives.",M:"14 in.",WS:"3+",BS:"3+",S:3,T:3,W:1,A:3,Ld:8,Sv:"5+"};
      let c14 = {name:"Khymerae",description:"The Warp-beasts called Khymerae are living proof of a Beastmasters' skills as a spirit-hunter. Each Khymera is a denizen of the chaotic dimension known as the Empyrean, born from the stuff of a Daemonworld. Khymerae set loose on the battlefields of realspace can wreak utter havoc before fading away like mist.",M:"10 in.",WS:"3+",BS:"-",S:4,T:4,W:1,A:3,Ld:4,Sv:"6+"};
      let c15 = {name:"Razorwing Flock",description:"Razorwing Flocks are possessed of an insatiable hunger for bone and they will fall upon their quarry with knife-sharp feathers and razored beaks, stripping flesh from frame in a hurricane of frantic motion. A well-trained Razorwing Flock will parade their blood-slicked and skeletal prize around and above their masters before tearing it apart in one final, savage feeding frenzy.",M:"12 in.",WS:"4+",BS:"-",S:2,T:2,W:4,A:4,Ld:4,Sv:"7+"};
      let c16 = {name:"Medusae",description:"The Medusae are unusual creatures, even in a place like Commorragh. They are highly empathic parasites that look like a collection of brains and spinal cords one atop another, and they float through the ether like jellyfish, feeding on daydreams and nightmares. When their visor is lifted, the Medusae will paralyse those under its gaze with a wave of raw anguish, plunging them into a coma from which there is no recovery.",M:"8 in.",WS:"3+",BS:"3+",S:3,T:3,W:3,A:1,Ld:8,Sv:"5+"};
      let c17 = {name:"Ur-Ghul",description:"Many dangerous creatures dwell in the depths of Commorragh - some are stealthy, viperous creatures, others are brutal killing machines. The Ur-Ghul fits into the latter category. While it may be entirely sightless, this wiry beast can sniff out its prey with uncanny accuracy and for this reason they make excellent hunters.",M:"8 in.",WS:"3+",BS:"-",S:4,T:3,W:3,A:4,Ld:2,Sv:"7+"};
      members = [c6,c7,c8,c9,c10,c11,c12,c13,c14,c15,c16,c17];
      let c18 = {name:"Talos",description:"Only the sickest minds could have created the bewildering Talos Pain Engine. From hooks to chains, to fat curved and serrated blades, there is an eye-watering array of barbaric implements. Within the armoured, shell-like carapace and scorpion-like aesthetic lurks a muscular beast that has been somehow blended with machine in the most horrific manner.",M:"8 in.",WS:"3+",BS:"4+",S:6,T:6,W:7,A:4,Ld:8,Sv:"3+"};
      let c19 = {name:"Reaver",description:"The Reavers of Commorragh are fascinated by the art of war at speed. They ride to battle upon the most streamlined and pared-down of all skycraft - the anti-grav jetbike, a perfect fusion of raw motive power and finely-honed lethality. The goal of every Reaver is to land a well-placed, fatal blow, to take off a head or slash open a throat with a single pass of their blade.",M:"16 in.",WS:"3+",BS:"3+",S:3,T:4,W:2,A:3,Ld:8,Sv:"4+"};
      let c20 = {name:"Cronos",description:"The Cronos Parasite Engine is a disturbing, bizarre creation and is used, much like the Talos, as a torture device and war machine.",M:"8 in.",WS:"4+",BS:"4+",S:5,T:6,W:7,A:3,Ld:9,Sv:"3+"};
      let c21 = {name:"Clawed Fiend",description:"The Clawed Fiend is a towering hulk of muscle and fur that has extremely advanced senses, able to see in several spectrums at once. A Clawed Fiend enters a berserk state when it is wounded - few warriors are quick enough to evade a raging Fiend that has scented the rotten tang of its own ichor.",M:"10 in.",WS:"4+",BS:"-",S:5,T:5,W:4,A:5,Ld:4,Sv:"5+"};
      let c22 = {name:"Grotesque",description:"These massive meat-hulks shamble forlornly after their macabre keepers, but when given the command to kill, they transform into engines of destruction. Their art of war is messy, brutal and utterly chaotic as they hack, chop and slice everything nearby, reducing them to little more than chunks of butchered meat swimming in pools of blood.",M:"7 in.",WS:"3+",BS:"6+",S:5,T:5,W:3,A:4,Ld:8,Sv:"6+"};
      monsters = [c18,c19,c20,c21,c22];
    }
    else if (codex.includes("genestealer")) {
      codex = "Genestealer Cult";
      let c1 = {name:"Primus",description:"The Primus is a commander in times of war, but whilst the cult still remains in hiding, it is his duty to spread the Genestealer Cult to other planets. His innate gift for leadership and coordination sees him militarize the cult in short order, masterminding the takeover of vehicles and even spacecraft. A strong champion and lauded hero amongst the brood, the Primus emerges only when the cult reaches a position of strength.",M:"6 in.",WS:"2+",BS:"3+",S:4,T:3,W:5,A:4,Ld:9,Sv:"5+"};
      let c2 = {name:"Magus",description:"The Magus plays a vital role in infiltrating a civilized society. Due to his intelligence, charisma, appearance, and understanding of the society being infiltrated, he is well suited to his role as mouthpiece of the clan to the outer society. The Magus is a special mutation which appears in a clan if a psychically-active species, such as humanity, is infiltrated.",M:"6 in.",WS:"3+",BS:"3+",S:3,T:3,W:4,A:3,Ld:8,Sv:"5+"};
      let c3 = {name:"Abominant",description:"A hulking brute in chains and shackles, accompanied by a mindwyrm familiar and clutching a power sledgehammer.",M:"6 in.",WS:"3+",BS:"6+",S:6,T:5,W:5,A:3,Ld:8,Sv:"5+"};
      leaders = [c1,c2,c3];
      let c4 = {name:"Acolyte",description:"Basking in the sheer alien glory of the patron that infected them, Acolyte Hybrids croon and hiss in the gloom. When the time comes to throw off the torn robes they use to disguise their foulness, the Acolyte Hybrids crawl up to the surface and into the sunlight, their grotesque faces twisted in subhuman glee.",M:"6 in.",WS:"3+",BS:"4+",S:4,T:3,W:1,A:3,Ld:8,Sv:"5+"};
      let c5 = {name:"Neophyte",description:"Weathered and toughened by a life of hard labour, each cultist features the inhuman reactions and strength their alien genes gift them. These third and fourth generation hybrids can pass as human – sinisterly, some can even infiltrate the Astra Militarum, such are their blessings.",M:"6 in.",WS:"4+",BS:"4+",S:3,T:3,W:1,A:2,Ld:8,Sv:"5+"};
      let c6 = {name:"Metamorphs",description:"When the day of the uprising arrives, it is the Hybrid Metamorphs that take pride of place upon the front line. In a storm of iron-hard claws, sinewy tentacles and slashing talons they crush and hack their way through everything in their path, an inspiration to the broodkin that worship them as sainted heroes of the cult.",M:"6 in.",WS:"3+",BS:"4+",S:4,T:3,W:1,A:4,Ld:8,Sv:"5+"};
      let c7 = {name:"Iconward",description:"Hoisting the sacred banner of his cult above the frenzied anarchy of their insurgency, the Acolyte Iconward is a focus both religious and military. Some Iconwards have spent centuries preparing for their incursion, and releasing this anticipation brings an infectious rush that inspires brood brothers to war.",M:"6 in.",WS:"3+",BS:"3+",S:4,T:3,W:4,A:4,Ld:8,Sv:"5+"};
      let c8 = {name:"Purestrain Genestealer",description:"Worshipped as the star-brethren of the Patriarch, the Purestrain Genestealers are stealthy predators that excel in times of war. These xenos creatures are terrifyingly agile and swift, able to squeeze through small spaces and track their prey across miles of urban decay. Their claws are diamond-hard and wickedly curved, natural weapons bred by the bio-fleets of the Tyranids to slice through the thickest armour or hide.",M:"8 in.",WS:"3+",BS:"-",S:4,T:4,W:1,A:3,Ld:9,Sv:"5+"};
      let c9 = {name:"Aberrant",description:"Misshapen, lumpen and inhumanly strong, the Aberrants are the repugnant offshoots of the Genestealer life cycle. Though dim-witted, their instinctive need to defend their brood makes them valuable assets to the cult. In battle, they battle with heavy industrial tools, moaning slurred praise to the Patriarch.",M:"6 in.",WS:"3+",BS:"6+",S:5,T:4,W:2,A:2,Ld:7,Sv:"5+"};
      members = [c4,c5,c6,c7,c8,c9];
      let c10 = {name:"Armoured Sentinel",description:"Bullets fly and shrapnel fills the air, but the Armoured Sentinels of the Genestealer Cults stride forward without pause. Those who underestimate the bravery of their cultist pilots will be made to pay with their lives, for when fighting as a squadron, these walkers can tear apart enemies far greater in bulk.",M:"8 in.",WS:"4+",BS:"4+",S:5,T:5,W:6,A:1,Ld:7,Sv:"3+"};
      let c11 = {name:"Scout Sentinel",description:"The Neophyte Hybrid pilots of these walkers peer through the gloom with unnatural intensity, refining their targeting solutions and stalking forward with the patience of true hunters until they have the perfect vantage point for launching their mechanised ambush. Suddenly, their trap is sprung in a storm of light and sound, and their unwitting foes fall by the dozen.",M:"9 in.",WS:"4+",BS:"4+",S:5,T:5,W:6,A:1,Ld:7,Sv:"4+"};
      let c12 = {name:"Patriarch",description:"Twice the height of a Space Marine and with strength enough to slice an Ogryn into bloody chunks, this creature is a leering nightmare of tooth and claw. In a flurry of whipping limbs and diamond-hard talons the Patriarch can tear through platoons of heavily armoured warriors and even light vehicles. Yet it is the hypnotic spell with which it binds its chosen hosts that mark it out as perhaps the most dangerous Tyranid yet encountered by the Imperium.",M:"8 in.",WS:"2+",BS:"5+",S:6,T:5,W:6,A:6,Ld:10,Sv:"4+"};
      monsters = [c10,c11,c12];
    }
    else if (codex.includes("tyranid")) {
      codex = "Tyranids";
      let c1 = {name:"Warrior Prime",description:"The Tyranid Warrior Prime serves as a powerful synapse creature for Tyranid swarms and is a potent commander of Tyranid attacks. The Tyranids’' leadership caste is difficult for Imperial commanders to identify, and there is often the mistaken assumption that the larger a Tyranid creature is, the more important it is to the swarm. This is a mistake that has cost more than one Imperial officer his rank and countless men their lives.",M:"6 in.",WS:"2+",BS:"3+",S:5,T:5,W:6,A:4,Ld:10,Sv:"3+"};
      let c2 = {name:"Ravener Prime",description:"Greater in strength, resilience and intelligence than its more common counterpart the Ravener, it's main purpose is tunneling under enemy lines to open up strategic tunnels for other elements of the swarm to use. With biomorphs almost rivaling those of the larger synapse creatures, it fulfills a battlefield role similar to the Tyranid Prime. It is the only variant of the Ravener capable of synaptic support.",M:"12 in.",WS:"2+",BS:"3+",S:5,T:5,W:6,A:4,Ld:10,Sv:"4+"};
      leaders = [c1,c2];
      let c3 = {name:"Zoanthrope",description:"Zoanthropes are powerful psykers, created solely to harness the psychic potential of the Hive Mind. By flexing the merest part of its mystical mind, a Zoanthrope can manifest this power in a variety of incredible, destructive ways.",M:"5 in.",WS:"4+",BS:"3+",S:4,T:4,W:3,A:1,Ld:9,Sv:"5+"};
      let c4 = {name:"Tyranid Warrior",description:"Tyranid Warriors are the most adaptable of all the Hive Mind’s bioforms. They are efficient killing machines with the ability to employ a wide variety of bio-weapon symbiotes. On the battlefield they are found fighting in both close quarters and at long range, and form a vital link in the Tyranid swarm, acting as relays through which the Hive Tyrants issue their commands.",M:"6 in.",WS:"3+",BS:"4+",S:4,T:4,W:3,A:3,Ld:9,Sv:"4+"};
      let c5 = {name:"Ravener",description:"Raveners were designed for shock assault and swift pursuit. They have incredible senses which allow them to track their prey over massive distances and detect the slightest movement, and a taut musculature that grants them terrifying speed. Raveners slither towards the foe with bewildering swiftness as their thorax-mounted weapon-symbiotes spit death.",M:"12 in.",WS:"3+",BS:"4+",S:4,T:4,W:3,A:4,Ld:5,Sv:"5+"};
      let c6 = {name:"Genestealer",description:"Genestealers are legendarily ferocious close combat opponents, with lightning fast reflexes and deadly claws, capable of ripping through adamantium. They have their own brood telepathy enabling them to function outside the range of the hive mind.",M:"8 in.",WS:"3+",BS:"-",S:4,T:4,W:1,A:3,Ld:9,Sv:"5+"};
      let c7 = {name:"Hormagaunt",description:"The Hormagaunt is a highly specialised Tyranid bioform. Each Hormagaunt has four razor-sharp claws specially developed for ripping and piercing flesh and armour, and powerful hind legs that allow the creature to dart into combat at an astounding speed.",M:"8 in.",WS:"4+",BS:"4+",S:3,T:3,W:1,A:2,Ld:5,Sv:"6+"};
      let c8 = {name:"Gargoyle",description:"Gargoyles are often the first wave of a Tyranid swarm to be seen in battle. Thus a Tyranid attack is preceded by the beating of thousands of membranous wings as Gargoyle Broods descend upon the foe; blocking out the sun, and spitting death from their fleshborers and caustic venom from their fanged mouths.",M:"12 in.",WS:"4+",BS:"4+",S:3,T:3,W:1,A:1,Ld:5,Sv:"6+"};
      let c9 = {name:"Termagant",description:"Termagants are fast, agile and cunning creatures. In planetary invasions, Termagants scuttle forward on four legs whilst unleashing torrents of fire from the anti-personnel bio-weaponry clutched in their clawed forelimbs.",M:"6 in.",WS:"4+",BS:"4+",S:3,T:3,W:1,A:1,Ld:5,Sv:"6+"};
      let c10 = {name:"Hive Guard",description:"Hive Guard are heavily armoured gun-beasts bound to extremely powerful symbiotic bio-weapons. They are created to guard the Tyranid Hive Ships and capillary towers that stand sentinel over prey worlds, until such time as intruders come within range of their deadly weapons.",M:"5 in.",WS:"4+",BS:"3+",S:4,T:5,W:3,A:2,Ld:7,Sv:"4+"};
      let c11 = {name:"Tyrant Guard",description:"Tyrant Guard are the ultimate bodyguards, it is the entire purpose of their creation to protect their Hive Tyrant. They take the form of colossal living shields, all but impervious to even the heaviest weapons.",M:"7 in.",WS:"3+",BS:"4+",S:5,T:5,W:3,A:2,Ld:6,Sv:"3+"};
      let c12 = {name:"Ripper Swarms",description:"Rippers are a small, maggot-like species of Tyranid that serve as the primary means of devouring bio-mass from a planet for a Tyranid Hive Fleet. Rippers are the most numerous of the Tyranid creatures, and in great swarms they can pull down and consume creatures many times their own size.",M:"6 in.",WS:"5+",BS:"5+",S:3,T:3,W:3,A:4,Ld:4,Sv:"6+"};
      let c13 = {name:"Slasher Swarm",description:"Sky-slashers are Rippers adapted to allow flight with the addition of bat-like wings. These winged terrors are increasingly common amongst Tyranid forces. The sky-mines of Kha'rull were completely overrun by Sky-slashers, and the automated defence batteries that had proven so effective against the larger winged Tyranid creatures were completely useless against the swarm of smaller and more maneuverable Rippers.",M:"12 in.",WS:"5+",BS:"5+",S:3,T:3,W:3,A:4,Ld:4,Sv:"6+"};
      members = [c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13];
      let c14 = {name:"Lictor",description:"Lictors rove ahead of the main Tyranid ground force, scouting the lay of the land and reporting back to the Hive Mind. Unusually for Tyranid organisms, their first instinct is not to feed, but rather to lurk in the shadows, out of sight and out of mind.",M:"9 in.",WS:"2+",BS:"4+",S:6,T:4,W:4,A:3,Ld:9,Sv:"5+"};
      let c15 = {name:"Pyrovore",description:"When confronted by a foe, the Pyrovore launches forth an incandescent fireball from its dorsal bio-weapon that reduces its victims to a pile of burning ash. As most opponents have learnt the hard way, the Pyrovore is best engaged at range.",M:"5 in.",WS:"4+",BS:"4+",S:4,T:4,W:4,A:2,Ld:5,Sv:"4+"};
      let c16 = {name:"Biovore",description:"Deep within its lumpen form, the Biovore nurtures a clutch of Spore Mines - living bombs that blanket the enemy in acids, poisons and shrapnel-sized pieces of chitin. A Biovore launches these Spore Mines through the air towards its enemy, where they detonate not on impact, but when it senses the proximity of a non-Tyranid life form.",M:"5 in.",WS:"4+",BS:"4+",S:4,T:4,W:4,A:2,Ld:5,Sv:"4+"};
      let c17 = {name:"Carnifex",description:"Carnifexes are living engines of destruction; towering monsters of unyielding armoured chitin and knotted alien muscle. They are one of the toughest and deadliest of all a hive fleet’s warrior creatures, their thunderous charges are akin to a living battering ram able to crush enemies and smash through obstacles with ease.",M:"7 in.",WS:"4+",BS:"4+",S:6,T:7,W:8,A:4,Ld:6,Sv:"3+"};
      let c18 = {name:"Venomthrope",description:"The Venomthrope's whip-like tentacles drip with a multitude of alien poisons. Indeed, so potent are these toxins that it is believed that a Venomthrope's very touch means certain death.",M:"5 in.",WS:"4+",BS:"4+",S:4,T:4,W:3,A:2,Ld:5,Sv:"5+"};
      monsters = [c14,c15,c16,c17,c18];
    }
    else if (codex.includes("eldar")) {
      codex = "Eldar";
      let c1 = {name:"Warlock",description:"Warlocks are Seers who once trod the Path of the Warrior, their previous experience as Aspect Warriors allows them to harness their more destructive impulses when using their psychic powers in combat.",M:"7 in.",WS:"3+",BS:"3+",S:3,T:3,W:2,A:2,Ld:8,Sv:"6+"};
      let c2 = {name:"Farseer",description:"Masters of prediction, the Farseers are the strangest and most visionary of a craftworld's advisors. Even in battle they can perform their divinations, casting the complex wraithbone runes of the Aeldari into the air and interpreting changes as the glowing icons orbit around them.",M:"7 in.",WS:"2+",BS:"2+",S:3,T:3,W:5,A:2,Ld:9,Sv:"6+"};
      let c3 = {name:"Spiritseer",description:"Spiritseers are those upon the Witch Path who are called to commune with the dead – a chilling concept, even amongst the Aeldari. Though Spiritseers help to ensure the survival of the entire Aeldari race, their actions are perceived by those around them as akin to necromancy; yet another depth the craftworlds must sink to in their struggle to stave off a lingering demise.",M:"7 in.",WS:"2+",BS:"2+",S:3,T:3,W:4,A:2,Ld:8,Sv:"6+"};
      leaders = [c1,c2,c3];
      let c4 = {name:"Ranger",description:"The rangers of the Aeldari are unparalleled scouts and expert marksmen. Known simply as 'Outcasts', the Rangers are the eyes and ears of the craftworlds, keeping a close eye on potential foes and reporting any sources of danger to the Farseers. In battle, the Rangers will scout ahead of the main force, taking up commanding positions on the battlefield.",M:"7 in.",WS:"3+",BS:"3+",S:3,T:3,W:1,A:1,Ld:7,Sv:"5+"};
      let c5 = {name:"Banshee",description:"Howling Banshees are swift and athletic troops who are most deadly in hand-to-hand fighting. Their banshee masks contain psychosonic amplifiers that magnify their keening battle screams into mind-destroying shockwaves. While their foes lie crippled and paralysed, the Banshees lay into them with precision and efficiency, their power swords cutting a blazing arc through the air around them as they sever heads from necks and limbs from torsos.",M:"8 in.",WS:"3+",BS:"3+",S:3,T:3,W:1,A:2,Ld:8,Sv:"4+"};
      let c6 = {name:"Windrider",description:"Swooping, jinking and arcing across the skies at unbelievable speed, turning at impossible angles, the Windriders are jetbike pilots completely in tune with their machines. Striking suddenly and violently with hailstorms of shuriken fire before climbing away with consummate grace, Windriders often destroy their prey even before the whine of their antigravitic engines broadcasts their presence.",M:"16 in.",WS:"3+",BS:"3+",S:3,T:4,W:2,A:1,Ld:7,Sv:"4+"};
      let c7 = {name:"Dark Reaper",description:"The Dark Reapers represent the War God in his role as the Destroyer. They are perhaps the most sinister and lethal of all Aspect Warriors and their armour is adorned with symbols of death and destruction.",M:"6 in.",WS:"3+",BS:"3+",S:3,T:3,W:1,A:1,Ld:8,Sv:"3+"};
      let c8 = {name:"Swooping Hawk",description:"The Swooping Hawks are the swift airborne support of the Aeldari warhost. They wear wings made of vibrating feather plates that incorporate small gravitic lifters, allowing them to soar high above the battlefield before swooping down on enemy units, firing into them with lasblasters and grenade packs, before disengaging and leaping back into the sky.",M:"14 in.",WS:"3+",BS:"3+",S:3,T:3,W:1,A:1,Ld:8,Sv:"4+"};
      let c9 = {name:"Striking Scorpion",description:"The Warrior Aspect of the Striking Scorpion epitomises the deadly attributes of their namesake, and they are the most potent of all the close assault aspects. They are merciless killers without exception, revelling in the hunt and the kill.",M:"7 in.",WS:"3+",BS:"3+",S:3,T:3,W:1,A:2,Ld:8,Sv:"3+"};
      let c10 = {name:"Warp Spider",description:"The Warp Spiders Aspect Warriors are the epitome of aggressive defence. Using a compact warp-generator housed within their armoured backpack, they can make short warp-jumps, disappearing and reappearing in the blink of an eye. This makes them the perfect ambush unit and many a foe has suddenly found themselves surrounded by heavily armoured Aeldari intent on destruction.",M:"7 in.",WS:"3+",BS:"3+",S:3,T:3,W:1,A:1,Ld:7,Sv:"3+"};
      let c11 = {name:"Fire Dragon",description:"The role of the Fire Dragons is to attack enemy strongholds and war machines, using their deadly weapons to destroy well-armoured troops and tanks. They carry fusion guns that can reduce an enemy to a cloud of superheated vapour in a second, or reduce a vehicle to little more than a lake of hot, molten metal.",M:"7 in.",WS:"3+",BS:"3+",S:3,T:3,W:1,A:1,Ld:8,Sv:"3+"};
      let c12 = {name:"Black Guardian",description:"Bursting into reality in a blaze of multicoloured light, the Black Guardians are Craftworld Ulthwé’s sharpest blades. A standing army, extremely skilled and utterly dedicated to the destruction of Chaos, they can strike from the webway, descending from wraithgates and attacking suddenly and with absolute force. After their prey is destroyed, the Black Guardians disappear without trace.",M:"7 in.",WS:"3+",BS:"3+",S:3,T:3,W:1,A:1,Ld:7,Sv:"5+"};
      let c13 = {name:"Dire Avenger",description:"The Dire Avengers are first amongst the Aspect Warriors of the Aeldari. They represent the War God's unending thirst for vengeance upon a galaxy of woe, and as such they are merciless to their foes and unstinting in their devotion to their people.",M:"7 in.",WS:"3+",BS:"3+",S:3,T:3,W:1,A:1,Ld:7,Sv:"4+"};
      let c14 = {name:"Guardian",description:"Guardians are primarily a defence force, employed when a craftworld becomes under threat or in battle where the Aspect Warriors are not numerous enough to overcome the enemy. Armed with shuriken catapults and heavy weapon platforms, they can unleash a deadly hail of fire.",M:"7 in.",WS:"3+",BS:"3+",S:3,T:3,W:1,A:1,Ld:7,Sv:"5+"};
      let c15 = {name:"Shadow Spectres Aspect Warrior",description:"Disguised behind shimmering holo-fields, draped with gossamer-thin robes and wraith-like in appearance, the Shadow Spectres were believed long lost by Aeldari Seers. Armed with prism rifles, each a potent anti-tank weapon, and equipped with jet packs, their mobility allows them to hunt down their chosen targets with the implacable patience of the dead, materialising seemingly from the very air to unleash their overwhelming firepower.",M:"12 in.",WS:"3+",BS:"3+",S:3,T:3,W:1,A:1,Ld:7,Sv:"5+"};
      let c16 = {name:"Corsair",description:"There are many bands of so-called Corsairs scattered across the galaxy, and all are savage and deadly raiders. Outcasts from the strict confines of the Craftworlds, the Corsairs live in self-imposed exile, seeking to explore the galaxy and experience the full gamut of emotion and sensation accessible to the Eldar’s sensitive psyche. Most are young and adventurous Eldar who will eventually return to their homes older, wiser and tempered by warfare.",M:"16 in.",WS:"3+",BS:"3+",S:3,T:3,W:1,A:1,Ld:6,Sv:"5+"};
      members = [c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14,c15,c16];
      let c17 = {name:"Shining Spear",description:"Moving faster than the eye can track, Shining Spears live for the thrill of the joust. Close-combat hit and run specialists, they charge headlong into their enemies, crackling laser lances ensuring the last thing an opposing force ever sees is a blur of silver and white, jinking and turning at speeds and angles impossible to follow.",M:"16 in.",WS:"3+",BS:"3+",S:3,T:4,W:3,A:3,Ld:8,Sv:"3+"};
      let c18 = {name:"Vyper",description:"Vypers are highly mobile weapons platforms, capable of laying down a withering fire even at high speed. Their speed more than makes up for their light armour.",M:"16 in.",WS:"6+",BS:"3+",S:4,T:5,W:6,A:1,Ld:8,Sv:"3+"};
      let c19 = {name:"Wraithblade",description:"Deadly close quarter fighters, Wraithblades are constructs made from wraithbone, imbued with the spirit stones of dead Aeldari.",M:"5 in.",WS:"3+",BS:"3+",S:5,T:5,W:3,A:2,Ld:9,Sv:"3+"};
      let c20 = {name:"Wraithguard",description:"Possessing deadly long-ranged weaponry, Wraithguard are constructs made from wraithbone, imbued with the spirit stones of dead Aeldari.",M:"5 in.",WS:"3+",BS:"3+",S:5,T:5,W:3,A:1,Ld:9,Sv:"3+"};
      let c21 = {name:"War Walker",description:"War Walkers are used in rough terrain, to scout out enemy positions. Its two heavy weapons provide a considerable arsenal for its size, but it lacks the armour to fight at the centre of an attack.",M:"10 in.",WS:"3+",BS:"3+",S:5,T:6,W:6,A:2,Ld:8,Sv:"4+"};
      let c22 = {name:"Wasp Assault Walker",description:"Commonly found amongst the raiding forces of the Aeldari Corsairs, the Aeldari Wasp Assault Walker confers additional protection and manoeuvrability to the pilot. Jump jets are added to the sturdy War Walker chassis to bolster this already potent weapons platform with deceptively swift movement.",M:"10 in.",WS:"3+",BS:"3+",S:5,T:6,W:7,A:2,Ld:8,Sv:"4+"};
      monsters = [c17,c18,c19,c20,c21,c22];
    }
    else if (codex.includes("necron")) {
      codex = "Necrons";
      let c1 = {name:"Cryptek",description:"Crypteks are members of pan-galactic conclaves of technologies whose purpose is to study and maintain the eldritch devices of their race. They are masters of dimensional dissonance, singularity manipulation, atomic transmutation, elemental transmogrification and countless other reason-defying technologies.",M:"5 in.",WS:"3+",BS:"3+",S:4,T:4,W:4,A:1,Ld:10,Sv:"4+"};
      let c2 = {name:"Overlord",description:"Commanding legion upon legion of deathless soldiers whose only purpose is to obey his every order, the Necron Overlord is a cold, calculating demigod. He has the pick of a multitude of arcane armaments of his ancient race – powerful artefacts that predate many of the galaxy’s greatest civilisations.",M:"5 in.",WS:"2+",BS:"2+",S:5,T:5,W:5,A:3,Ld:10,Sv:"3+"};
      let c3 = {name:"Lord",description:"When a Necron Lord strides forth in his raiment of war, only the strongest and canniest of enemies have any hope of survival. His armoured form is proof against tank-busting weaponry and his metal hands can crush bones to powder in the blink of an eye.",M:"5 in.",WS:"3+",BS:"3+",S:5,T:5,W:4,A:3,Ld:10,Sv:"3+"};
      let c4 = {name:"Destroyer Lord",description:"Destroyer Lords are the most maniacal of their kind. This is chiefly because they retain far more intellect than baseline Destroyers, and can bring all of this fearsome intelligence to bear in their pursuit of galactic conquests. Destroyer Lords remain worthy of mention as something truly horrific. Where others kill for pleasure, or in service to some malignant god, Destroyer Lords pursue their bloody crusade simply because it is their chosen course.",M:"10 in.",WS:"3+",BS:"3+",S:5,T:6,W:6,A:4,Ld:10,Sv:"3+"};
      leaders = [c1,c2,c3,c4];
      let c5 = {name:"Lychguard",description:"The Lychguard are the wardens of the nobility, said to be utterly dedicated to their charges. While most Necrons wear a suit of living metal, the Lychguard wear huge suits of ancient armour.",M:"5 in.",WS:"3+",BS:"3+",S:5,T:5,W:2,A:2,Ld:10,Sv:"3+"};
      let c6 = {name:"Immortal",description:"As the shock troops of the Necron army, a phalanx of Immortals will strive for victory using every tactic at their disposal. They can easily withstand a hail of heavy bolter fire.",M:"5 in.",WS:"3+",BS:"3+",S:4,T:4,W:1,A:1,Ld:10,Sv:"3+"};
      let c7 = {name:"Praetorian",description:"As the Necrons stir ever more into wakefulness, the Triarch Praetorians have re-emerged to join the dynastic legions. Triarch Praetorians hold a great responsibility - to ensure that the Necron dynasties never fall.",M:"10 in.",WS:"3+",BS:"3+",S:5,T:5,W:2,A:2,Ld:10,Sv:"3+"};
      let c8 = {name:"Deathmark",description:"For countless millennia, Deathmark Squads have served the Necron nobility as snipers and assassins. They can effectively slip in and out of dimensions at will.",M:"5 in.",WS:"3+",BS:"3+",S:4,T:4,W:1,A:1,Ld:10,Sv:"3+"};
      let c9 = {name:"Necron Warrior",description:"Necron Warriors form the cold heart of a Tomb World's armies. They are implacable, emotionless and terrifying soldiers - the inexorable emissaries of death itself. Unlike higher ranking Necrons, the basic warrior is little more than an automaton slaved to the will of their commander. What Necron Warriors lack in intuition they more than make up for in determination and durability.",M:"5 in.",WS:"3+",BS:"3+",S:4,T:4,W:1,A:1,Ld:10,Sv:"4+"};
      let c10 = {name:"Scarabs",description:"A Scarab is a small, silver, beetle-like Necron construct. These robotic Scarabs are the most numerous and diverse of the Necrons' Canoptek machine servants. They are designed to break down organic and non-organic matter into raw energy, which can then be woven into fresh construct forms at the direction of the Scarabs’ controller.",M:"10 in.",WS:"4+",BS:"-",S:3,T:3,W:3,A:4,Ld:10,Sv:"6+"};
      let c11 = {name:"Destroyer",description:"Destroyers are the deranged agents of annihilation whose sole reason for existence is centred around an unshakeable yearning to quench the flames of life. On the battlefield, they will shatter enemy formations with heavy fire, before swooping down upon the survivors to ensure that none remain alive.",M:"10 in.",WS:"3+",BS:"3+",S:4,T:5,W:3,A:2,Ld:10,Sv:"3+"};
      let c12 = {name:"Heavy Destroyer",description:"A Destroyer cares not for borders or allegiance, nor does he make any distinction between the innocent and the damned - all life is his enemy and all living creatures are his prey. Like their lighter brethren, Heavy Destroyers are the fusion of a Necron Immortal and a flying skimmer craft.",M:"10 in.",WS:"3+",BS:"3+",S:4,T:5,W:3,A:2,Ld:10,Sv:"3+"};
      let c13 = {name:"Flayed Ones",description:"The flayer curse was a parting gift from the C'tan known as Llandu'gor, the flayer. Over time, those Necrons tainted with the curse suffer a slow and tortuous erosion of sanity. Where other Necrons are cold and calculating, these infected warriors begin to take pleasure in death and carnage, wrapping skin and torn flesh around them like grisly trophies.",M:"5 in.",WS:"3+",BS:"6+",S:4,T:4,W:1,A:3,Ld:10,Sv:"4+"};
      members = [c5,c6,c7,c8,c9,c10,c11,c12,c13];
      let c14 = {name:"Tomb Blade",description:"The Tomb Blade has a curious motion for a craft of its design, eschewing the arrow-straight attack vectors of other jetbikes and fighter craft. It often corkscrews across the battlefield rather than taking a more direction approach. No flesh and blood pilot could ever hope to contend with such an anarchic approach without succumbing to blackouts and nausea, but such hazards have no hold over machines.",M:"14 in.",WS:"3+",BS:"3+",S:4,T:5,W:2,A:1,Ld:10,Sv:"4+"};
      let c15 = {name:"Wraith",description:"While a Tomb World slumbers, Canoptek Wraiths are its eyes and ears. Canoptek Wraiths flit silently through the dusty halls, patrolling for intruders and inspecting systems for damage and decay. Their most notable feature is their dimensional destabilisation matrix - a phase shifter that allows them to skip in and out of reality. ",M:"12 in.",WS:"3+",BS:"3+",S:6,T:5,W:3,A:3,Ld:10,Sv:"4+"};
      let c16 = {name:"Canoptek Spyder",description:"Unlike their Necron masters, Canoptek Spyders never sleep, but while away the aeons servicing the structures of their Tomb World. Though the Canoptek Spyder is essentially an automated drone, it is still a formidable foe when the situation demands. Any enemy foolish enough to stray within reach of the Canoptek Spyder will have flesh scoured from bone by an array of mechanical tools and pincers.",M:"6 in.",WS:"4+",BS:"4+",S:6,T:6,W:4,A:4,Ld:10,Sv:"3+"};
      let c17 = {name:"Canoptek Acanthrites",description:"Resembling monstrous, artificial insects enfolded in shadowed wings of tenebrous force that propel them through the skies, Canoptek Acanthrites are murderous Necron constructs created for a single purpose – the destruction of those who have dared to claim the worlds of the ancient Necron empire as their own. Their agile, coiling tails are tipped with hyper-phased voidblades and they are armed with high-powered thermal cutting beams, and this potent armament allows them to carve and dissemble solid matter with horrifying speed. Unsurprisingly, when these devastating weapons are turned upon frail flesh the results are terrible to behold.",M:"12 in.",WS:"3+",BS:"3+",S:5,T:5,W:3,A:3,Ld:10,Sv:"3+"};
      monsters = [c14,c15,c16,c17];
    }
    else if (codex.includes("ork")) {
      codex = "Orks";
      let c1 = {name:"Big Mek",description:"Big Meks are obsessed with creating ever larger and more devastating war machines to unleash upon their foes. Their (often calamitous) endeavours have spawned some deadly dakka.",M:"5 in.",WS:"3+",BS:"5+",S:5,T:4,W:4,A:3,Ld:7,Sv:"4+"};
      let c2 = {name:"Painboy",description:"Painboys are at home amongst the blood and horror of the battlefield, eagerly patching up lost limbs, doing a spot of welding on a broken face or furnishing the Warboss with a brand new flame-throwing arm. They learn their craft through a mixture of instinct, trial and error, and the time-honoured principles of ‘Orky know-wotz’.",M:"5 in.",WS:"3+",BS:"5+",S:5,T:5,W:5,A:4,Ld:6,Sv:"4+"};
      let c3 = {name:"Weirdboy",description:"Weirdboyz are the most psychically powerful of all Orks as they act as a focal point for the psychic energy generated by their greenskin comrades. Orks are generally pretty rowdy, and as a result the Weirdboy can pick up quite a lot of psychic energy which can, unless dissipated, prove spectacularly fatal for him.",M:"5 in.",WS:"3+",BS:"5+",S:5,T:4,W:4,A:3,Ld:6,Sv:"6+"};
      let c4 = {name:"Mek",description:"Ork Meks are eccentric inventors that possess a natural ability for creating wotzits and fixin' gubbinz. From building deadly dakka from scrap to creating wobbling bubbles of force to protect da boyz from harm, Meks can do it all.",M:"5 in.",WS:"3+",BS:"5+",S:4,T:4,W:3,A:2,Ld:6,Sv:"6+"};
      let c5 = {name:"Warboss",description:"As the leader of the Warband the Warboss gets first pick of any wargear and the best fighters to make up his bodyguard. This tends to make an Ork Warboss even more deadly than he already is.",M:"5 in.",WS:"2+",BS:"5+",S:6,T:5,W:6,A:4,Ld:8,Sv:"4+"};
      leaders = [c1,c2,c3,c4,c5];
      let c6 = {name:"Meganobz",description:"The Meganobz are the richest and most battle-hardened Nobz around. Clad in Mek-built mega armour (with enough protective plating to turn the wearer into a walking tank), these Nobz can shrug off the hail of bullets that would kill lesser Orks.",M:"4 in.",WS:"3+",BS:"5+",S:5,T:4,W:3,A:3,Ld:6,Sv:"2+"};
      let c7 = {name:"Warbiker",description:"A Warbiker treats his personal steed with real care, because a warbike is not only a thing of great prestige but also a direct conduit to the adrenaline-rich thrill of speed. Nothing short of dive-bombing the foe in a fighta-bomma can compare to the raw excitement of hurtling towards the enemy on a warbike with all guns blazing.",M:"14 in.",WS:"3+",BS:"5+",S:4,T:5,W:2,A:2,Ld:6,Sv:"4+"};
      let c8 = {name:"Flash Git",description:"Behold the Flash Gitz! The richest and most obnoxious of all the Orks. These wanton mercenaries travel the galaxy flaunting their flashy kit and engaging in acts of outrageous piracy. But don’t be fooled by their ostentation. A mob of Gitz are exceptionally skilled at breaking ‘eads and they are lethal in a firefight - Gork knows when they open fire it's nothing short of cataclysmic.",M:"5 in.",WS:"3+",BS:"5+",S:5,T:4,W:2,A:3,Ld:6,Sv:"6+"};
      let c9 = {name:"Ork Boy",description:"Boyz are the rank and file of an Ork army. Orks are tough, determined fighters who fall upon the enemy in great tides of howling violence. Generally armed with the heavy, solid-shot, slugga and brutal, edged choppas, they blow great gouges from the enemy before hacking them apart.",M:"5 in.",WS:"3+",BS:"5+",S:4,T:4,W:1,A:2,Ld:6,Sv:"6+"};
      let c10 = {name:"Tankbusta",description:"Ork Tankbustas live for the big kill, preferring to wield a rokkit launcha in battle as opposed to the choppas and sluggas more commonly associated with their race. It is their role on the battlefield to hunt down enemy tanks and blow them to smithereens with well-aimed (in other words, lucky) salvoes of rokkits.",M:"5 in.",WS:"3+",BS:"5+",S:4,T:4,W:1,A:2,Ld:6,Sv:"6+"};
      let c11 = {name:"Ork Kommando",description:"A Kommando is an Ork Boy specialist who prefers to rely on 'kunning trikz' instead of fighting his opponents head-on like most other Greenskins. Kommandoz serve as the Orks' infiltrators and saboteurs, and are masters of the arts of stealth, ambush, unconventional tactics and striking at the opponent from a totally unexpected quarter.",M:"6 in.",WS:"3+",BS:"5+",S:4,T:4,W:1,A:2,Ld:6,Sv:"6+"};
      let c12 = {name:"Stormboy",description:"Stormboyz, the shock troops of many successful warbands, dedicate their lives to the time honoured martial disciplines of drilling, marching and hurtling through the air. To this end they go to war strapped to rokkit packs that, when activated propel their wearers forward on great tongues of oily black flame.",M:"12 in.",WS:"3+",BS:"5+",S:4,T:4,W:1,A:2,Ld:6,Sv:"6+"};
      let c13 = {name:"Loota",description:"These wiry and muscular Ork models stand wearing an array of bizarre contraptions held up with huge, crude leather straps or bandaged together with material. Some of them wear unusual masks and goggles, others decide to physically sport the tools of their trade – and spanners and wrenches can be discerned above their head or fixed to their bodies.",M:"5 in.",WS:"3+",BS:"5+",S:4,T:4,W:1,A:2,Ld:6,Sv:"6+"};
      let c14 = {name:"Nob",description:"The Orks call their ruling caste Nobz. Nobz are bigger and scarier than other Orks and revel in cruel or casual violence. Nobz lead by example, plunging into the thick of the fighting and breaking skulls left, right and centre. In this way each Nob acts as a sergeant-at-arms, champion, oppressor and role model for the Boyz they lead.",M:"5 in.",WS:"3+",BS:"5+",S:5,T:4,W:2,A:3,Ld:6,Sv:"4+"};
      let c15 = {name:"Burna",description:"Some of them wear unusual masks and goggles, others decide to physically sport the tools of their trade – and spanners and wrenches can be discerned above their head or fixed to their bodies. Each of them carries an enormous burna and occasionally their toothy maws can be seen poking out underneath all of these gizmos.",M:"5 in.",WS:"3+",BS:"5+",S:4,T:4,W:1,A:2,Ld:6,Sv:"6+"};
      let c16 = {name:"Gretchins",description:"Gretchin mobs make up for their shocking lack of quality with sheer quantity. The natural cowardice and feeble-limbed incompetence of the Gretchin race does not predispose them to the arts of war, and a typical Grot would prefer to have his head buried in a sporehole than to actually participate in a proper battle.",M:"5 in.",WS:"5+",BS:"4+",S:2,T:2,W:1,A:1,Ld:4,Sv:"6+"};
      members = [c6,c7,c8,c9,c10,c11,c12,c13,c14,c15,c16];
      let c17 = {name:"Killa Kan",description:"Killa Kans are essentially giant metal canisters on piston-driven legs that sport lethal close combat attachments and heavy-duty weaponry. One of their limbs usually ends in deadly-looking power shears or a great blood-encrusted buzz saw, whilst the other is a large calibre weapon welded to the opposite side.",M:"6 in.",WS:"5+",BS:"4+",S:5,T:5,W:5,A:3,Ld:6,Sv:"3+"};
      let c18 = {name:"DeffKopta",description:"Deffkoptas are the lunatic inventions of Meks obsessed with flight. Each Deffkoptra is a one-man attack craft that has a set of whirring rotors mounted above the pilot's head and a jet booster at the rear. Deffkoptas scream across the battlefield their underslung weapons spitting death.",M:"14 in.",WS:"3+",BS:"5+",S:4,T:5,W:4,A:2,Ld:6,Sv:"4+"};
      let c19 = {name:"Warbuggy",description:"Warbuggies are two-man attack vehicles that combine the raw speed of a Warbike with a formidable weapon payload. Those Speed Freaks who own Warbuggies will group together in ramshackle bands that hurtle around the battlefield, blasting away at anything they can.",M:"14 in.",WS:"3+",BS:"5+",S:4,T:5,W:5,A:4,Ld:6,Sv:"4+"};
      let c20 = {name:"Wartrakk",description:"Most warbands are accompanied by a ramshackle band of vehicles that hurtle around the battlefield shooting at anything they can. A squadron may contain a mix of Wartrakks and Warbuggies.",M:"12 in.",WS:"3+",BS:"5+",S:4,T:5,W:6,A:4,Ld:6,Sv:"4+"};
      let c21 = {name:"Grot Tank",description:"The lunatic product of the deranged imaginations of grot riggers and scavs that have spent far too long basking in the insane genius of the Big Meks, Grots Tanks are diminutive armoured vehicles made to imitate the far larger Ork Wagons and Tanks.",M:"2D6 in.",WS:"6+",BS:"4+",S:4,T:5,W:4,A:3,Ld:5,Sv:"4+"};
      monsters = [c17,c18,c19,c20,c21];
    }
    else if (codex.includes("tau")) {
      codex = "T'au Empire";
      let c1 = {name:"Marksman",description:"Ensconced in cover far from the front lines of battle, a Firesight Marksman scans the battlefield, using advanced optical sights to select prime targets. Above him float the rest of his team -- a group of Sniper Drones, each of them equipped with an underslung Longshot Pulse Rifle.",M:"5 in.",WS:"5+",BS:"3+",S:3,T:3,W:3,A:2,Ld:7,Sv:"4+"};
      let c2 = {name:"Cadre Fireblade",description:"Fireblades are the most grizzled and seasoned Fire Warriors of their cadre, whose skill at the Fire Warrior's art leads them to eschew battlesuit technology. They are excellent field leaders and their long experience has taught them exactly where to place shots to maximise damage.",M:"6 in.",WS:"3+",BS:"2+",S:3,T:3,W:5,A:3,Ld:8,Sv:"4+"};
      let c3 = {name:"Ethereal",description:"Little is known of the T'au Ethereal caste, appearing as shrouded, enigmatic figures that eschew the advance equipment favoured by the T'au Fire caste. Ethereals seem to combine the roles of priesthood and royalty within T'au society and command unquestioning loyalty from all of the other castes.",M:"6 in.",WS:"3+",BS:"4+",S:3,T:3,W:4,A:3,Ld:9,Sv:"5+"};
      let c4 = {name:"Kroot Shaper",description:"The job of a shaper is to direct the evolution of the Kroot in their Kindred by consuming certain enemies. For example, if a Shaper wanted his Kindred to become more muscular, he would have them pursue Orks, likewise a Shaper who wanted more agile or swift Kroot, they would hunt Eldar.",M:"7 in.",WS:"3+",BS:"4+",S:3,T:3,W:5,A:3,Ld:7,Sv:"6+"};
      leaders = [c1,c2,c3,c4];
      let c5 = {name:"Pathfinder",description:"Light reconnaissance units, Pathfinder Teams are the eyes and ears of their Commander in a way no drone can yet emulate. A Pathfinder's foremost role is not to engage the enemy, but instead to operate ahead of their comrades, close to their foe, to accurately scout the enemy.",M:"7 in.",WS:"5+",BS:"4+",S:3,T:3,W:1,A:2,Ld:7,Sv:"5+"};
      let c6 = {name:"Fire Warrior",description:"Not only is the path ahead illuminated by the light of the Greater Good, but also the glow of pulse rifles. The courageous Fire Warriors, with the absolute, zealous belief in the destiny of their race, fight with unstoppable fervour and enviable skill. Benefiting from the astonishing rate of technological advance displayed by T'au engineers, their armour is lightweight yet durable and their weaponry reliable yet powerful.",M:"6 in.",WS:"5+",BS:"4+",S:3,T:3,W:1,A:2,Ld:7,Sv:"4+"};
      let c7 = {name:"Breacher",description:"The Fire Warriors Breacher Team specialises in brutally effective close-range assaults, clearing buildings of threats in a tight, tactical formation and delivering sharp, shockingly sudden frontline displays of raw incendiary power that grind enemy soldiers into dust, discharging pulse blasters and hurling photon grenades until they are certain every path is clear.",M:"6 in.",WS:"5+",BS:"4+",S:3,T:3,W:1,A:2,Ld:7,Sv:"4+"};
      let c8 = {name:"Vespid",description:"Many alien races are found to be working alongside their T'au overseers - one of these races is the Vespid Stingwings. They function as auxiliaries to T'au armies, and the T'au value them for their skill at negotiating dangerous ground at high speed. Stingwings make ideal mobile reserve or flanking troops, though the T'au rely on the communion helm issued to the Strain Leaders to communicate with the Stingwings and coordinate their actions.",M:"14 in.",WS:"4+",BS:"4+",S:3,T:4,W:1,A:2,Ld:8,Sv:"4+"};
      let c9 = {name:"Kroot Carnivore",description:"Kroot are a species of savage humanoids who are a member species of the T’au who evolved from avian creatures. Kroot are tall aliens , their avian ancestry giving them a bird-like beak and long quills protruding from their heads like hair. Smaller quills, possibly the evolutionary remnants of feathers, can be found scattered over their bodies.",M:"7 in.",WS:"3+",BS:"4+",S:3,T:3,W:1,A:1,Ld:6,Sv:"6+"};
      let c10 = {name:"Stealth Battlesuit",description:"Equipped with the latest XV25 Stealth Armour these troops are the 'lone wolves' of the T'au army, operating independently of other formations.",M:"8 in.",WS:"5+",BS:"4+",S:4,T:4,W:2,A:3,Ld:8,Sv:"3+"};
      let c11 = {name:"Kroot Hound",description:"Many alien races are found to be working alongside their T'au overseers - one of these races is the Kroot, which originated on the world of Pech, a forested world located in the north-west of the T'au Empire. Kroot Hounds are ridden by Kroot into battle - they are deadly and notoriously bad-tempered beasts.",M:"12 in.",WS:"3+",BS:"-",S:3,T:3,W:1,A:2,Ld:5,Sv:"6+"};
      let c12 = {name:"Drones",description:"Darting through even the most hostile environments with ease, T'au Drones are guided by a networked AI of impressive capabilities. Data flows back and forth constantly between them, advising and distributing information on threats, optimal paths and targets instantaneously, creating a blanket of tactical firepower across entire battlefields. Were these drones merely information-gatherers they would be dangerous enough, but their abilities to create shields, mark targets and destroy enemies make them immensely useful offensive weapons as well as the definition of machine-cunning.",M:"8 in.",WS:"5+",BS:"5+",S:3,T:4,W:1,A:1,Ld:6,Sv:"4+"};
      members = [c5,c6,c7,c8,c9,c10,c11,c12];
      let c13 = {name:"Krootox Rider",description:"Kroot musculature is extremely powerful and composed of dense fibre spindles with a greater power to mass ratio than is found in humans. In battle the Kroot lash large, unwieldy Kroot guns to the powerful shoulders of the Krootox, using the beast as a mobile weapon platform.",M:"7 in.",WS:"3+",BS:"4+",S:6,T:5,W:4,A:2,Ld:6,Sv:"6+"};
      let c14 = {name:"Crisis Battlesuit",description:"Skimming along on the jets of their repulsor engines, Crisis Battlesuits close on their enemy with a surprising speed, unloading their diverse weaponry and leaping away in a split second. Only the best T'au warriors are allowed to pilot these machines, spending years on the front line before even being considered for this honour. Able to be dropped from a planet's upper atmosphere, slamming into ranks of enemies like a tidal wave, the XV8 Crisis Battlesuit is the ultimate balance of firepower, speed and resilience.",M:"8 in.",WS:"5+",BS:"4+",S:5,T:5,W:3,A:3,Ld:8,Sv:"3+"};
      let c15 = {name:"Broadside",description:"Designed to offer long-range support, the XV88 Broadside Battlesuit has exceeded expectations, becoming a mainstay of the Hunter Cadres and tank-killers of legendary proportions. Powered by a particle accelerator, a Broadside's heavy rail rifle shot can penetrate the thickest plasteel bunkers.",M:"5 in.",WS:"5+",BS:"4+",S:5,T:5,W:6,A:3,Ld:8,Sv:"2+"};
      let c16 = {name:"Pathfinder Tetras",description:"Light scout vehicle used by T'au Pathfinders to designate targets for Seeker Missiles.",M:"18 in.",WS:"6+",BS:"4+",S:4,T:5,W:4,A:2,Ld:6,Sv:"4+"};
      let c17 = {name:"Hazard Suit",description:"The most cutting-edge of the battlesuit technology utilised by the Fire Caste of the T'au Empire, the XV-9 'Hazard' Close Support Armour is an original battlesuit design intended to act as a powerful counter-attack unit and weapons platform.",M:"8 in.",WS:"5+",BS:"4+",S:5,T:5,W:5,A:3,Ld:8,Sv:"3+"};
      let c18 = {name:"Piranha",description:"The Piranha is a lightly armoured vehicle used by the T'au in a range of capacities, including rapid response, support of pathfinder teams and even as battlefield transport for high-ranking dignitaries. By Upgrading the vehicle to carry a fusion blaster or a pair of seeker missiles it becomes an effective tank hunter, particularly when guided to a target by Pathfinder teams.",M:"16 in.",WS:"6+",BS:"4+",S:4,T:5,W:6,A:2,Ld:6,Sv:"4+"};
      monsters = [c13,c14,c15,c16,c17,c18];
    }


    this.navCtrl.push(ChooseTeamPage, {
         'codex' : codex,
         'leaders' : leaders,
          'members' : members,
          'monsters' : monsters
       });



  }

}
